// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/resource_handle.proto

package org.tensorflow.proto.framework;

/**
 * <pre>
 * Protocol buffer representing a handle to a tensorflow resource. Handles are
 * not valid across executions, but can be serialized back and forth from within
 * a single run.
 * </pre>
 *
 * Protobuf type {@code tensorflow.ResourceHandleProto}
 */
public  final class ResourceHandleProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.ResourceHandleProto)
    ResourceHandleProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceHandleProto.newBuilder() to construct.
  private ResourceHandleProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceHandleProto() {
    device_ = "";
    container_ = "";
    name_ = "";
    maybeTypeName_ = "";
    dtypesAndShapes_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceHandleProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceHandleProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            device_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            container_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 32: {

            hashCode_ = input.readUInt64();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            maybeTypeName_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              dtypesAndShapes_ = new java.util.ArrayList<DtypeAndShape>();
              mutable_bitField0_ |= 0x00000001;
            }
            dtypesAndShapes_.add(
                input.readMessage(DtypeAndShape.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        dtypesAndShapes_ = java.util.Collections.unmodifiableList(dtypesAndShapes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResourceHandleProto.class, Builder.class);
  }

  public interface DtypeAndShapeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.ResourceHandleProto.DtypeAndShape)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.DataType dtype = 1;</code>
     */
    int getDtypeValue();

    /**
     * <code>.tensorflow.DataType dtype = 1;</code>
     */
    DataType getDtype();

    /**
     * <code>.tensorflow.TensorShapeProto shape = 2;</code>
     */
    boolean hasShape();

    /**
     * <code>.tensorflow.TensorShapeProto shape = 2;</code>
     */
    TensorShapeProto getShape();

    /**
     * <code>.tensorflow.TensorShapeProto shape = 2;</code>
     */
    TensorShapeProtoOrBuilder getShapeOrBuilder();
  }
  /**
   * <pre>
   * Protocol buffer representing a pair of (data type, tensor shape).
   * </pre>
   *
   * Protobuf type {@code tensorflow.ResourceHandleProto.DtypeAndShape}
   */
  public  static final class DtypeAndShape extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.ResourceHandleProto.DtypeAndShape)
      DtypeAndShapeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DtypeAndShape.newBuilder() to construct.
    private DtypeAndShape(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DtypeAndShape() {
      dtype_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DtypeAndShape();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DtypeAndShape(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dtype_ = rawValue;
              break;
            }
            case 18: {
              TensorShapeProto.Builder subBuilder = null;
              if (shape_ != null) {
                subBuilder = shape_.toBuilder();
              }
              shape_ = input.readMessage(TensorShapeProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(shape_);
                shape_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_DtypeAndShape_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_DtypeAndShape_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DtypeAndShape.class, Builder.class);
    }

    public static final int DTYPE_FIELD_NUMBER = 1;
    private int dtype_;

    /**
     * <code>.tensorflow.DataType dtype = 1;</code>
     */
    public int getDtypeValue() {
      return dtype_;
    }

    /**
     * <code>.tensorflow.DataType dtype = 1;</code>
     */
    public DataType getDtype() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dtype_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int SHAPE_FIELD_NUMBER = 2;
    private TensorShapeProto shape_;

    /**
     * <code>.tensorflow.TensorShapeProto shape = 2;</code>
     */
    public boolean hasShape() {
      return shape_ != null;
    }

    /**
     * <code>.tensorflow.TensorShapeProto shape = 2;</code>
     */
    public TensorShapeProto getShape() {
      return shape_ == null ? TensorShapeProto.getDefaultInstance() : shape_;
    }

    /**
     * <code>.tensorflow.TensorShapeProto shape = 2;</code>
     */
    public TensorShapeProtoOrBuilder getShapeOrBuilder() {
      return getShape();
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dtype_ != DataType.DT_INVALID.getNumber()) {
        output.writeEnum(1, dtype_);
      }
      if (shape_ != null) {
        output.writeMessage(2, getShape());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dtype_ != DataType.DT_INVALID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, dtype_);
      }
      if (shape_ != null) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getShape());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof DtypeAndShape)) {
        return super.equals(obj);
      }
      DtypeAndShape other = (DtypeAndShape) obj;

      if (dtype_ != other.dtype_) {
        return false;
      }
      if (hasShape() != other.hasShape()) {
        return false;
      }
      if (hasShape()) {
        if (!getShape()
            .equals(other.getShape())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DTYPE_FIELD_NUMBER;
      hash = (53 * hash) + dtype_;
      if (hasShape()) {
        hash = (37 * hash) + SHAPE_FIELD_NUMBER;
        hash = (53 * hash) + getShape().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DtypeAndShape parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static DtypeAndShape parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static DtypeAndShape parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static DtypeAndShape parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static DtypeAndShape parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static DtypeAndShape parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static DtypeAndShape parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static DtypeAndShape parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static DtypeAndShape parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static DtypeAndShape parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static DtypeAndShape parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static DtypeAndShape parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(DtypeAndShape prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * Protocol buffer representing a pair of (data type, tensor shape).
     * </pre>
     *
     * Protobuf type {@code tensorflow.ResourceHandleProto.DtypeAndShape}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.ResourceHandleProto.DtypeAndShape)
        DtypeAndShapeOrBuilder {

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_DtypeAndShape_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_DtypeAndShape_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DtypeAndShape.class, Builder.class);
      }

      // Construct using org.tensorflow.proto.framework.ResourceHandleProto.DtypeAndShape.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }

      @Override
      public Builder clear() {
        super.clear();
        dtype_ = 0;

        if (shapeBuilder_ == null) {
          shape_ = null;
        } else {
          shape_ = null;
          shapeBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_DtypeAndShape_descriptor;
      }

      @Override
      public DtypeAndShape getDefaultInstanceForType() {
        return DtypeAndShape.getDefaultInstance();
      }

      @Override
      public DtypeAndShape build() {
        DtypeAndShape result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DtypeAndShape buildPartial() {
        DtypeAndShape result = new DtypeAndShape(this);
        result.dtype_ = dtype_;
        if (shapeBuilder_ == null) {
          result.shape_ = shape_;
        } else {
          result.shape_ = shapeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }

      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }

      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DtypeAndShape) {
          return mergeFrom((DtypeAndShape) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DtypeAndShape other) {
        if (other == DtypeAndShape.getDefaultInstance()) {
          return this;
        }
        if (other.dtype_ != 0) {
          setDtypeValue(other.getDtypeValue());
        }
        if (other.hasShape()) {
          mergeShape(other.getShape());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DtypeAndShape parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DtypeAndShape) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dtype_ = 0;
      /**
       * <code>.tensorflow.DataType dtype = 1;</code>
       */
      public int getDtypeValue() {
        return dtype_;
      }
      /**
       * <code>.tensorflow.DataType dtype = 1;</code>
       */
      public Builder setDtypeValue(int value) {
        dtype_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>.tensorflow.DataType dtype = 1;</code>
       */
      public DataType getDtype() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dtype_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }

      /**
       * <code>.tensorflow.DataType dtype = 1;</code>
       */
      public Builder setDtype(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        dtype_ = value.getNumber();
        onChanged();
        return this;
      }

      /**
       * <code>.tensorflow.DataType dtype = 1;</code>
       */
      public Builder clearDtype() {
        
        dtype_ = 0;
        onChanged();
        return this;
      }

      private TensorShapeProto shape_;
      private com.google.protobuf.SingleFieldBuilderV3<
          TensorShapeProto, TensorShapeProto.Builder, TensorShapeProtoOrBuilder> shapeBuilder_;

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public boolean hasShape() {
        return shapeBuilder_ != null || shape_ != null;
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public TensorShapeProto getShape() {
        if (shapeBuilder_ == null) {
          return shape_ == null ? TensorShapeProto.getDefaultInstance() : shape_;
        } else {
          return shapeBuilder_.getMessage();
        }
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public Builder setShape(TensorShapeProto value) {
        if (shapeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shape_ = value;
          onChanged();
        } else {
          shapeBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public Builder setShape(
          TensorShapeProto.Builder builderForValue) {
        if (shapeBuilder_ == null) {
          shape_ = builderForValue.build();
          onChanged();
        } else {
          shapeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public Builder mergeShape(TensorShapeProto value) {
        if (shapeBuilder_ == null) {
          if (shape_ != null) {
            shape_ =
                TensorShapeProto.newBuilder(shape_).mergeFrom(value).buildPartial();
          } else {
            shape_ = value;
          }
          onChanged();
        } else {
          shapeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public Builder clearShape() {
        if (shapeBuilder_ == null) {
          shape_ = null;
          onChanged();
        } else {
          shape_ = null;
          shapeBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public TensorShapeProto.Builder getShapeBuilder() {

        onChanged();
        return getShapeFieldBuilder().getBuilder();
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      public TensorShapeProtoOrBuilder getShapeOrBuilder() {
        if (shapeBuilder_ != null) {
          return shapeBuilder_.getMessageOrBuilder();
        } else {
          return shape_ == null ?
              TensorShapeProto.getDefaultInstance() : shape_;
        }
      }

      /**
       * <code>.tensorflow.TensorShapeProto shape = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TensorShapeProto, TensorShapeProto.Builder, TensorShapeProtoOrBuilder>
          getShapeFieldBuilder() {
        if (shapeBuilder_ == null) {
          shapeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TensorShapeProto, TensorShapeProto.Builder, TensorShapeProtoOrBuilder>(
              getShape(),
              getParentForChildren(),
              isClean());
          shape_ = null;
        }
        return shapeBuilder_;
      }

      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.ResourceHandleProto.DtypeAndShape)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.ResourceHandleProto.DtypeAndShape)
    private static final DtypeAndShape DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DtypeAndShape();
    }

    public static DtypeAndShape getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DtypeAndShape>
        PARSER = new com.google.protobuf.AbstractParser<DtypeAndShape>() {
      @Override
      public DtypeAndShape parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DtypeAndShape(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DtypeAndShape> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DtypeAndShape> getParserForType() {
      return PARSER;
    }

    @Override
    public DtypeAndShape getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DEVICE_FIELD_NUMBER = 1;
  private volatile Object device_;

  /**
   * <pre>
   * Unique name for the device containing the resource.
   * </pre>
   *
   * <code>string device = 1;</code>
   */
  public String getDevice() {
    Object ref = device_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      device_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * Unique name for the device containing the resource.
   * </pre>
   *
   * <code>string device = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceBytes() {
    Object ref = device_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      device_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTAINER_FIELD_NUMBER = 2;
  private volatile Object container_;

  /**
   * <pre>
   * Container in which this resource is placed.
   * </pre>
   *
   * <code>string container = 2;</code>
   */
  public String getContainer() {
    Object ref = container_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      container_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * Container in which this resource is placed.
   * </pre>
   *
   * <code>string container = 2;</code>
   */
  public com.google.protobuf.ByteString
      getContainerBytes() {
    Object ref = container_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      container_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile Object name_;

  /**
   * <pre>
   * Unique name of this resource.
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * Unique name of this resource.
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASH_CODE_FIELD_NUMBER = 4;
  private long hashCode_;
  /**
   * <pre>
   * Hash code for the type of the resource. Is only valid in the same device
   * and in the same execution.
   * </pre>
   *
   * <code>uint64 hash_code = 4;</code>
   */
  public long getHashCode() {
    return hashCode_;
  }

  public static final int MAYBE_TYPE_NAME_FIELD_NUMBER = 5;
  private volatile Object maybeTypeName_;

  /**
   * <pre>
   * For debug-only, the name of the type pointed to by this handle, if
   * available.
   * </pre>
   *
   * <code>string maybe_type_name = 5;</code>
   */
  public String getMaybeTypeName() {
    Object ref = maybeTypeName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      maybeTypeName_ = s;
      return s;
    }
  }

  /**
   * <pre>
   * For debug-only, the name of the type pointed to by this handle, if
   * available.
   * </pre>
   *
   * <code>string maybe_type_name = 5;</code>
   */
  public com.google.protobuf.ByteString
      getMaybeTypeNameBytes() {
    Object ref = maybeTypeName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      maybeTypeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DTYPES_AND_SHAPES_FIELD_NUMBER = 6;
  private java.util.List<DtypeAndShape> dtypesAndShapes_;

  /**
   * <pre>
   * Data types and shapes for the underlying resource.
   * </pre>
   *
   * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
   */
  public java.util.List<DtypeAndShape> getDtypesAndShapesList() {
    return dtypesAndShapes_;
  }

  /**
   * <pre>
   * Data types and shapes for the underlying resource.
   * </pre>
   *
   * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
   */
  public java.util.List<? extends DtypeAndShapeOrBuilder>
  getDtypesAndShapesOrBuilderList() {
    return dtypesAndShapes_;
  }

  /**
   * <pre>
   * Data types and shapes for the underlying resource.
   * </pre>
   *
   * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
   */
  public int getDtypesAndShapesCount() {
    return dtypesAndShapes_.size();
  }

  /**
   * <pre>
   * Data types and shapes for the underlying resource.
   * </pre>
   *
   * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
   */
  public DtypeAndShape getDtypesAndShapes(int index) {
    return dtypesAndShapes_.get(index);
  }

  /**
   * <pre>
   * Data types and shapes for the underlying resource.
   * </pre>
   *
   * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
   */
  public DtypeAndShapeOrBuilder getDtypesAndShapesOrBuilder(
      int index) {
    return dtypesAndShapes_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDeviceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, device_);
    }
    if (!getContainerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, container_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (hashCode_ != 0L) {
      output.writeUInt64(4, hashCode_);
    }
    if (!getMaybeTypeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, maybeTypeName_);
    }
    for (int i = 0; i < dtypesAndShapes_.size(); i++) {
      output.writeMessage(6, dtypesAndShapes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDeviceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, device_);
    }
    if (!getContainerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, container_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (hashCode_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, hashCode_);
    }
    if (!getMaybeTypeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, maybeTypeName_);
    }
    for (int i = 0; i < dtypesAndShapes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, dtypesAndShapes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof ResourceHandleProto)) {
      return super.equals(obj);
    }
    ResourceHandleProto other = (ResourceHandleProto) obj;

    if (!getDevice()
        .equals(other.getDevice())) {
      return false;
    }
    if (!getContainer()
        .equals(other.getContainer())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getHashCode()
        != other.getHashCode()) return false;
    if (!getMaybeTypeName()
        .equals(other.getMaybeTypeName())) return false;
    if (!getDtypesAndShapesList()
        .equals(other.getDtypesAndShapesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICE_FIELD_NUMBER;
    hash = (53 * hash) + getDevice().hashCode();
    hash = (37 * hash) + CONTAINER_FIELD_NUMBER;
    hash = (53 * hash) + getContainer().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + HASH_CODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHashCode());
    hash = (37 * hash) + MAYBE_TYPE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMaybeTypeName().hashCode();
    if (getDtypesAndShapesCount() > 0) {
      hash = (37 * hash) + DTYPES_AND_SHAPES_FIELD_NUMBER;
      hash = (53 * hash) + getDtypesAndShapesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResourceHandleProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ResourceHandleProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ResourceHandleProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ResourceHandleProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ResourceHandleProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ResourceHandleProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ResourceHandleProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static ResourceHandleProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ResourceHandleProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ResourceHandleProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static ResourceHandleProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static ResourceHandleProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(ResourceHandleProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Protocol buffer representing a handle to a tensorflow resource. Handles are
   * not valid across executions, but can be serialized back and forth from within
   * a single run.
   * </pre>
   *
   * Protobuf type {@code tensorflow.ResourceHandleProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.ResourceHandleProto)
      ResourceHandleProtoOrBuilder {

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResourceHandleProto.class, Builder.class);
    }

    // Construct using org.tensorflow.proto.framework.ResourceHandleProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getDtypesAndShapesFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      device_ = "";

      container_ = "";

      name_ = "";

      hashCode_ = 0L;

      maybeTypeName_ = "";

      if (dtypesAndShapesBuilder_ == null) {
        dtypesAndShapes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dtypesAndShapesBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return ResourceHandle.internal_static_tensorflow_ResourceHandleProto_descriptor;
    }

    @Override
    public ResourceHandleProto getDefaultInstanceForType() {
      return ResourceHandleProto.getDefaultInstance();
    }

    @Override
    public ResourceHandleProto build() {
      ResourceHandleProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ResourceHandleProto buildPartial() {
      ResourceHandleProto result = new ResourceHandleProto(this);
      int from_bitField0_ = bitField0_;
      result.device_ = device_;
      result.container_ = container_;
      result.name_ = name_;
      result.hashCode_ = hashCode_;
      result.maybeTypeName_ = maybeTypeName_;
      if (dtypesAndShapesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          dtypesAndShapes_ = java.util.Collections.unmodifiableList(dtypesAndShapes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dtypesAndShapes_ = dtypesAndShapes_;
      } else {
        result.dtypesAndShapes_ = dtypesAndShapesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResourceHandleProto) {
        return mergeFrom((ResourceHandleProto) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResourceHandleProto other) {
      if (other == ResourceHandleProto.getDefaultInstance()) {
        return this;
      }
      if (!other.getDevice().isEmpty()) {
        device_ = other.device_;
        onChanged();
      }
      if (!other.getContainer().isEmpty()) {
        container_ = other.container_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getHashCode() != 0L) {
        setHashCode(other.getHashCode());
      }
      if (!other.getMaybeTypeName().isEmpty()) {
        maybeTypeName_ = other.maybeTypeName_;
        onChanged();
      }
      if (dtypesAndShapesBuilder_ == null) {
        if (!other.dtypesAndShapes_.isEmpty()) {
          if (dtypesAndShapes_.isEmpty()) {
            dtypesAndShapes_ = other.dtypesAndShapes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDtypesAndShapesIsMutable();
            dtypesAndShapes_.addAll(other.dtypesAndShapes_);
          }
          onChanged();
        }
      } else {
        if (!other.dtypesAndShapes_.isEmpty()) {
          if (dtypesAndShapesBuilder_.isEmpty()) {
            dtypesAndShapesBuilder_.dispose();
            dtypesAndShapesBuilder_ = null;
            dtypesAndShapes_ = other.dtypesAndShapes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dtypesAndShapesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDtypesAndShapesFieldBuilder() : null;
          } else {
            dtypesAndShapesBuilder_.addAllMessages(other.dtypesAndShapes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ResourceHandleProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ResourceHandleProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object device_ = "";

    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     */
    public String getDevice() {
      Object ref = device_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        device_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      Object ref = device_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     */
    public Builder setDevice(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      device_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     */
    public Builder clearDevice() {
      
      device_ = getDefaultInstance().getDevice();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     */
    public Builder setDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      device_ = value;
      onChanged();
      return this;
    }

    private Object container_ = "";

    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     */
    public String getContainer() {
      Object ref = container_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        container_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContainerBytes() {
      Object ref = container_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        container_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     */
    public Builder setContainer(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      container_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     */
    public Builder clearContainer() {
      
      container_ = getDefaultInstance().getContainer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     */
    public Builder setContainerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      container_ = value;
      onChanged();
      return this;
    }

    private Object name_ = "";

    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public Builder setName(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      name_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long hashCode_ ;
    /**
     * <pre>
     * Hash code for the type of the resource. Is only valid in the same device
     * and in the same execution.
     * </pre>
     *
     * <code>uint64 hash_code = 4;</code>
     */
    public long getHashCode() {
      return hashCode_;
    }
    /**
     * <pre>
     * Hash code for the type of the resource. Is only valid in the same device
     * and in the same execution.
     * </pre>
     *
     * <code>uint64 hash_code = 4;</code>
     */
    public Builder setHashCode(long value) {
      
      hashCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hash code for the type of the resource. Is only valid in the same device
     * and in the same execution.
     * </pre>
     *
     * <code>uint64 hash_code = 4;</code>
     */
    public Builder clearHashCode() {
      
      hashCode_ = 0L;
      onChanged();
      return this;
    }

    private Object maybeTypeName_ = "";

    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     */
    public String getMaybeTypeName() {
      Object ref = maybeTypeName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        maybeTypeName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMaybeTypeNameBytes() {
      Object ref = maybeTypeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        maybeTypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     */
    public Builder setMaybeTypeName(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      maybeTypeName_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     */
    public Builder clearMaybeTypeName() {
      
      maybeTypeName_ = getDefaultInstance().getMaybeTypeName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     */
    public Builder setMaybeTypeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      maybeTypeName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<DtypeAndShape> dtypesAndShapes_ =
        java.util.Collections.emptyList();
    private void ensureDtypesAndShapesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dtypesAndShapes_ = new java.util.ArrayList<DtypeAndShape>(dtypesAndShapes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        DtypeAndShape, DtypeAndShape.Builder, DtypeAndShapeOrBuilder> dtypesAndShapesBuilder_;

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public java.util.List<DtypeAndShape> getDtypesAndShapesList() {
      if (dtypesAndShapesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dtypesAndShapes_);
      } else {
        return dtypesAndShapesBuilder_.getMessageList();
      }
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public int getDtypesAndShapesCount() {
      if (dtypesAndShapesBuilder_ == null) {
        return dtypesAndShapes_.size();
      } else {
        return dtypesAndShapesBuilder_.getCount();
      }
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public DtypeAndShape getDtypesAndShapes(int index) {
      if (dtypesAndShapesBuilder_ == null) {
        return dtypesAndShapes_.get(index);
      } else {
        return dtypesAndShapesBuilder_.getMessage(index);
      }
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder setDtypesAndShapes(
        int index, DtypeAndShape value) {
      if (dtypesAndShapesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.set(index, value);
        onChanged();
      } else {
        dtypesAndShapesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder setDtypesAndShapes(
        int index, DtypeAndShape.Builder builderForValue) {
      if (dtypesAndShapesBuilder_ == null) {
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.set(index, builderForValue.build());
        onChanged();
      } else {
        dtypesAndShapesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder addDtypesAndShapes(DtypeAndShape value) {
      if (dtypesAndShapesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.add(value);
        onChanged();
      } else {
        dtypesAndShapesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder addDtypesAndShapes(
        int index, DtypeAndShape value) {
      if (dtypesAndShapesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.add(index, value);
        onChanged();
      } else {
        dtypesAndShapesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder addDtypesAndShapes(
        DtypeAndShape.Builder builderForValue) {
      if (dtypesAndShapesBuilder_ == null) {
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.add(builderForValue.build());
        onChanged();
      } else {
        dtypesAndShapesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder addDtypesAndShapes(
        int index, DtypeAndShape.Builder builderForValue) {
      if (dtypesAndShapesBuilder_ == null) {
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.add(index, builderForValue.build());
        onChanged();
      } else {
        dtypesAndShapesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder addAllDtypesAndShapes(
        Iterable<? extends DtypeAndShape> values) {
      if (dtypesAndShapesBuilder_ == null) {
        ensureDtypesAndShapesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dtypesAndShapes_);
        onChanged();
      } else {
        dtypesAndShapesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder clearDtypesAndShapes() {
      if (dtypesAndShapesBuilder_ == null) {
        dtypesAndShapes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dtypesAndShapesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public Builder removeDtypesAndShapes(int index) {
      if (dtypesAndShapesBuilder_ == null) {
        ensureDtypesAndShapesIsMutable();
        dtypesAndShapes_.remove(index);
        onChanged();
      } else {
        dtypesAndShapesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public DtypeAndShape.Builder getDtypesAndShapesBuilder(
        int index) {
      return getDtypesAndShapesFieldBuilder().getBuilder(index);
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public DtypeAndShapeOrBuilder getDtypesAndShapesOrBuilder(
        int index) {
      if (dtypesAndShapesBuilder_ == null) {
        return dtypesAndShapes_.get(index);
      } else {
        return dtypesAndShapesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public java.util.List<? extends DtypeAndShapeOrBuilder>
    getDtypesAndShapesOrBuilderList() {
      if (dtypesAndShapesBuilder_ != null) {
        return dtypesAndShapesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dtypesAndShapes_);
      }
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public DtypeAndShape.Builder addDtypesAndShapesBuilder() {
      return getDtypesAndShapesFieldBuilder().addBuilder(
          DtypeAndShape.getDefaultInstance());
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public DtypeAndShape.Builder addDtypesAndShapesBuilder(
        int index) {
      return getDtypesAndShapesFieldBuilder().addBuilder(
          index, DtypeAndShape.getDefaultInstance());
    }

    /**
     * <pre>
     * Data types and shapes for the underlying resource.
     * </pre>
     *
     * <code>repeated .tensorflow.ResourceHandleProto.DtypeAndShape dtypes_and_shapes = 6;</code>
     */
    public java.util.List<DtypeAndShape.Builder>
    getDtypesAndShapesBuilderList() {
      return getDtypesAndShapesFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        DtypeAndShape, DtypeAndShape.Builder, DtypeAndShapeOrBuilder>
    getDtypesAndShapesFieldBuilder() {
      if (dtypesAndShapesBuilder_ == null) {
        dtypesAndShapesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            DtypeAndShape, DtypeAndShape.Builder, DtypeAndShapeOrBuilder>(
            dtypesAndShapes_,
            ((bitField0_ & 0x00000001) != 0),
            getParentForChildren(),
            isClean());
        dtypesAndShapes_ = null;
      }
      return dtypesAndShapesBuilder_;
    }

    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.ResourceHandleProto)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.ResourceHandleProto)
  private static final ResourceHandleProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResourceHandleProto();
  }

  public static ResourceHandleProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceHandleProto>
      PARSER = new com.google.protobuf.AbstractParser<ResourceHandleProto>() {
    @Override
    public ResourceHandleProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceHandleProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceHandleProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResourceHandleProto> getParserForType() {
    return PARSER;
  }

  @Override
  public ResourceHandleProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

