workspace(name = "tensorflow_core_api")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# TensorFlow archive
# Note: Make sure to synchronize Maven dependencies inherited from TensorFlow binaries when updating
# the version of this archive (e.g. google protobuf)
http_archive(
    name = "org_tensorflow",
    patches = [
        ":tensorflow-windows.patch", # https://github.com/tensorflow/tensorflow/issues/25213
        ":tensorflow-proto.patch",
        ":tensorflow-api-def.patch"
    ],
    patch_tool = "patch",
    patch_args = ["-p1"],
    patch_cmds = ["grep -rl 'java_package' tensorflow/core | xargs sed -i.bak 's/^\(.* java_package = \"org\.tensorflow\.\)\(.*\"\)/\\1proto.\\2'/"],
    urls = [
       "https://github.com/tensorflow/tensorflow/archive/v2.2.0-rc2.tar.gz",
    ],
    sha256 = "3e0cffc98ad3767dd16a09b7f25a99961e21d65cfcad67ed3a9b1a01318c7e94",
    strip_prefix = "tensorflow-2.2.0-rc2"
)

# START: Upstream TensorFlow dependencies
# TensorFlow build depends on these dependencies.
# Needs to be in-sync with TensorFlow sources.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
    strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2019-06-13
    ],
)
# END: Upstream TensorFlow dependencies

load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@upb//bazel:repository_defs.bzl", "bazel_version_repository")
bazel_version_repository(name = "bazel_version")
