name: "Check generation is committed"
description: "Ensure that all code generation is present in the commits"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git add .
        git update-index --refresh
        git diff-index --quiet --exit-code HEAD tensorflow-core/tensorflow-core-api/src/gen/** || \
          (git --no-pager diff HEAD -- ; echo "::error file=changes.txt,line=0,title=\"Un-commited generation\"::Generated classes after build do not match what was committed" ; exit 1)