op {
  visibility: VISIBLE
  graph_op_name: "RetrieveTPUEmbeddingProximalAdagradParametersGradAccumDebug"
  endpoint {
    name: "tpu.RetrieveTPUEmbeddingProximalAdagradParametersGradAccumDebug"
  }
}
