op {
  graph_op_name: "XlaSparseDenseMatmulCustomCombinerOnTcGradWithAdagradAndCsrInput"
  visibility: VISIBLE
  endpoint {
    name: "xla.XlaSparseDenseMatmulCustomCombinerOnTcGradWithAdagradAndCsrInput"
  }
}
