op {
  visibility: VISIBLE
  graph_op_name: "SegmentSumV2"
  endpoint {
    name: "math.SegmentSum"
  }
  description: <<END
Read
[the section on segmentation](https://tensorflow.org/api_docs/python/tf/math#Segmentation)
for an explanation of segments.

Computes a tensor such that
\\(output_i = \sum_j data_j\\) where sum is over `j` such
that `segment_ids[j] == i`.

If the sum is empty for a given segment ID `i`, `output[i] = 0`.

Note that this op is currently only supported with jit_compile=True.

END
}
