op {
  graph_op_name: "XlaSparseDenseMatmulCustomCombinerOnTcGradWithAdamAndCsrInput"
  visibility: VISIBLE
  endpoint {
    name: "xla.XlaSparseDenseMatmulCustomCombinerOnTcGradWithAdamAndCsrInput"
  }
}
