FROM maven:3.8.6-jdk-11

WORKDIR /root
RUN curl -L https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_x64_linux_hotspot_17.0.13_11.tar.gz -o openjdk-17.tar.gz
RUN tar zxvf openjdk-17.tar.gz
ENV JAVA_HOME /root/jdk-17.0.13+11/

